### ISSUE TITLE
C01_status issue

### ISSUE THREAD

**Issue by Guimli355** [NaomiMod/Rent-A-Hero-No1#18] opened 2022-09-22 19:28 UTC
The status shows : silly combo and no charge move, but front kick combo and a charge move is selected.
![IMG_20220922_210743](https://user-images.githubusercontent.com/113843539/191834332-f402fcc7-0f70-4c97-8c7d-890882faa994.jpg)
![IMG_20220922_210808](https://user-images.githubusercontent.com/113843539/191834348-ff602efc-8b99-49ec-a895-79ddd180dee6.jpg)

**Comment by Guimli355** [comment] 2022-09-23 20:30
I have the same issue with the Japanese version.

**Comment by ToddlerPichu** [comment] 2022-09-23 21:52
I am not sure if I am understanding correctly, are you saying "COMBO: XXX" stays unchanged even when selecting another combo in moves? If so it appears to work for me... and if I misunderstood please disregard
![shot45](https://user-images.githubusercontent.com/41944249/192061547-b4d8bc41-fe29-4388-b55f-5aff0bf97e16.png)

**Comment by ToddlerPichu** [comment] 2022-09-23 22:11
As for the issue with it being unchangeable in the JP version for you, I think I can explain that. I have been able to reproduce the bug with loading my EN save file up on a JP rom, however on my clean JP save file ive been playing side by side, it functions normally. 
I still do not know why combo's name was not changing for you in the EN translation, but in the JP original it is almost certainly because you loaded your EN save file to test it

**Comment by Guimli355** [comment] 2022-09-23 22:14
You understood well. But I will try something tomorrow, maybe the status screen change if you are in normal mode or hero mode. Maybe that if I am in normal mode : only silly combo is available, so the status shows that.I will try to check the status before and after a transformation

**Comment by Guimli355** [comment] 2022-09-23 22:17
It's strange... I will try to create a new Japanese save file tomorrow to check if it's ok.

**Comment by ToddlerPichu** [comment] 2022-09-23 22:27
> Maybe that if I am in normal mode : only silly combo is available, so the status shows that.I will try to check the status before and after a transformation

AH... yes, that does seem to be the issue. I was not reproducing the issue because it was a clean JP save vs the EN translation, it was because I was untransformed. Untransformed you will always have "Silly Combo" as your combo. 

Thank you for this revelation and judging by your screenshot you were in non hero forme, so this issue is solved and I will close it.

**Closed by ToddlerPichu** 2022-09-23 22:27 UTC
